[project]
name = "stylo-flora"
requires-python = ">=3.10"
dependencies = [
  "absl-py",
  "bs4",
  "bert_score",
  "codebleu",
  "datasets",
  "dotenv",
  "evaluate",
  "google-genai",
  "javalang",
  "jpype1",
  "jsonlines",
  "lxml",
  "nltk",
  "openai",
  "rouge_score",
  "seaborn",
  "tiktoken",
  "transformers",  # 4.40.2 for codegeex4 compatibility, 4.51.3 for phi-4 compatibility
  "tree-sitter-cpp<0.23",
  "tree-sitter-java<0.23",
  "tree-sitter-python<0.23",
]
version = "0.1.0"
readme = {file = "README.md", content-type = "text/markdown"}
description = "A Python package for spanning code corpus to variants with code style transformations and evaluating them."

[project.optional-dependencies]
dev = [
  "ipykernel",
  "websockets",
]

[build-system]
requires = ["flit_core>=3.6"]
build-backend = "flit_core.buildapi"

[tool.mypy]
mypy_path = "src"

[[tool.mypy.overrides]]
module = [
  "codebleu",
  "datasets",
  "evaluate",
  "google.*",
  "javalang",
  "jpype.*",
  "jsonlines",
  "nltk.*",
  "org.*", # modules from StyleX
  "pandas",
  "torch",
  "tqdm",
  "transformers",
  "tree_sitter",
  "tree_sitter_java",
  "yaml",
]
ignore_missing_imports = true
