transformer:
  class: org.example.experiment.Mutator
  retry: 3
  max_workers: 8

agent:
  ######### settings for remote API #########
  timeout: 120
  retry: 3
  retry_interval: 5
  max_workers: 5

  ######## settings for local models ########
  max_new_tokens: 1024

logger:
  max_bytes: 5242880 # 5MB
  backup_count: 5

metrics:
  target_dir: targets/ # the path where compiled files are stored
  result_dir: results/ # the path where evaluation results are stored
  timeout: 60 # unit: seconds
  max_workers: 8
