mutator:
  class: org.example.experiment.Mutator

translator:
  prompts:
    prologue: "<task>
                Translate code from one language to another without changing functionality.
               </task>
               <constraint>
                1. Your output MUST only contain the translated code without any explanations for direct compilation, enclosed by triple back quotes.
                2. If the target language is C++, you MUST use `using namespace std;` and convert function names from camel case to snake case.
                3. If the target_declaration is empty, ignore it.
               </constraint>"

  ######### settings for remote API #########
  timeout: 120
  retry: 3
  retry_interval: 5
  max_workers: 10

  ######## settings for local models ########
  max_new_tokens: 1024

logger:
  max_bytes: 5242880 # 5MB
  backup_count: 5
  verbose: true

evaluator:
  target_dir: target/ # the path where compiled files are stored
  timeout: 60 # unit: seconds
  max_workers: 8
