rules:
  - id: 0
  - id: 1
  - id: 2
  - id: 3
  - id: 4
  - id: 5
  - id: 6
  - id: 7
  - id: 8
  - id: 9
  - id: 10
    name: Optional Braces
    granularity: statement
    patterns:
    callback: optional_braces
  - id: 11
    name: One Variable Per Declaration Statement
    granularity: statement
    patterns:
    callback: one_variable_per_declaration_statement
  - id: 12
    name: Assignment Statement Preferences
    granularity: statement
    patterns:
      - |
        (assignment_expression
            left: (identifier) @var
        ) @stmt
      - |
        (assignment_expression
          left: (identifier) @var
          right: (binary_expression
            left: (identifier) @var2 (#eq? @var @var2)
          )
        ) @stmt
      - |
        (assignment_expression
          left: (identifier) @var
          operator: "="
          right: (binary_expression
            right: (identifier) @var2 (#eq? @var @var2)
          )
        ) @stmt
    edges:
      - [0, 1]
    callback: assignment_statement_preferences
  - id: 13
    name: Increment/Decrement Preferences
    granularity: statement
    patterns:
      - |
        (update_expression
            (identifier) @var
            ["++" "--"] @op
        ) @stmt
      - |
        (update_expression
            ["++" "--"] @op
            (identifier) @var
        ) @stmt
      - |
        (assignment_expression
            left: (identifier) @var
            operator: ["+=" "-="] @op
            right: (decimal_integer_literal) @ltr (#eq? @ltr "1")
        ) @stmt
    edges:
      - [0, 2]
      - [1, 2]
    callback: increment_decrement_preferences
    note: Excludes the case where the variable is used as function argument or array index.
  - id: 14
    name: Continuous Logic AND Conditions Preferences
    granularity: statement
    patterns:
      - |
        (if_statement
          condition: (parenthesized_expression
            (binary_expression
              left: (_) @cond1
              operator: "&&"
              right: (_) @cond2
            )
          )
          consequence: (_) @blk
        ) @stmt
      - |
        (if_statement
          condition: (parenthesized_expression
            (_) @cond1
          )
          consequence: (block
            (if_statement
              condition: (parenthesized_expression
                (_) @cond2
              )
              consequence: (_) @blk
            )
          )
        ) @stmt
      - |
        (if_statement
          condition: (parenthesized_expression
            (_) @cond1
          )
          consequence: (if_statement
              condition: (parenthesized_expression
                (_) @cond2
              )
              consequence: (_) @blk
          )
        ) @stmt
    edges:
      - [0, 1]
    callback: continuous_logic_and_conditions_preferences
    note: Decouples this rule from the rule of optional braces; generalizes to include nested if statements.
  - id: 15
    name: Continuous Logic OR Conditions Preferences
    granularity: statement
    patterns:
    edges:
      - [0, 1]
    callback: continuous_logic_or_conditions_preferences
    note: Ditto.
