transformer:
  max_workers: 4

agent:
  max_new_tokens: 32768

  ######### settings for remote API #########
  timeout: 120
  sleep: 1
  retries: 3
  retry_interval: 30

logger:
  max_bytes: 5242880 # 5MB
  backup_count: 5

metrics:
  timeout: 30 # unit: seconds
  max_workers: 4
