datasets:
  xcodeeval_root: data/xCodeEval
  codescope_root: data/CodeScope
  classeval_t_root: data/ClassEval-T
  testbench_root: data/TestBench

transformer:
  max_workers: 4

agent:
  max_new_tokens: 65536

  ######### settings for remote API #########
  timeout: 180
  sleep: 1
  retries: 3
  retry_interval: 30

logger:
  max_bytes: 5242880 # 5MB
  backup_count: 5

metrics:
  timeout: 120 # unit: seconds
  max_workers: 4
