transformer:
  class: org.example.Mutator
  max_workers: 1

agent:
  ######### settings for remote API #########
  timeout: 120
  sleep: 1
  retry: 3
  retry_interval: 30
  max_workers: 3

  ######## settings for local models ########
  max_new_tokens: 2048

logger:
  max_bytes: 5242880 # 5MB
  backup_count: 5

metrics:
  timeout: 30 # unit: seconds
  max_workers: 8
