- IndentionStyler:
  - indention_unit:  # control `indentionUnit` and `indentionType` simultaneously
      option_type: enum
      options:
        - TAB
        - TWO_SPACES
        - FOUR_SPACES

- SpaceStyler:
  - operator_spacing:
      option_type: bool

  # - parenthetical_spacing:
  #     option_type: bool

  # - control_flow_spacing:
  #     option_type: bool

  - method_call_spacing:
      option_type: bool

  - delimiter_spacing:
      option_type: bool

- NewlineStyler:
  - member_padding:
      option_type: bool

  - block_padding:
      option_type: bool

  - declaration_padding:
      option_type: bool

- IntraNewlineStyler:
  - long_line_wrapping:
      option_type: bool

# - InterNewlineStyler:

- BodyLayoutStyler:
  - break_before_brace:
      option_type: bool

- OptionalBraceStyler:
  - omit_braces:  # control `useBrace` (for all possible contexts)
      option_type: bool

- ModifierOrderStyler:
  - order:  # control `order`
      option_type: enum
      options:
        - STANDARD
        - REVERSED

- DeclarationLayoutStyler:
  - merge_declarations:  # control `mergeVar`
      option_type: bool

- StructureStyler:  #  control `preferenceIndex` for each `EquivalentStructure`
  - 1:  # inc
      option_type: number
      length: 5

  - 2:  # dec
      option_type: number
      length: 4

  - 3:  # assignment1
      option_type: number
      length: 2

  - 4:  # nesting_if
      option_type: number
      length: 2

  - 5:  # cascading_if
      option_type: number
      length: 2

  - 6:  # loop_empty
      option_type: number
      length: 2

  - 7:  # loop1
      option_type: number
      length: 2

  - 8:  # loop2
      option_type: number
      length: 3

  - 9:  # loop3
      option_type: number
      length: 2

  - 10:  # loop4
      option_type: number
      length: 2

  - 11:  # loop5
      option_type: number
      length: 2

  - 12:  # loop6
      option_type: number
      length: 2

  - 13:  # check_then_return
      option_type: number
      length: 2

  - 14:  # dec_then_check_assign
      option_type: number
      length: 4

  - 15:  # check_then_assign
      option_type: number
      length: 3

  - 16:  # op_preference1
      option_type: number
      length: 2

  - 17:  # op_preference2
      option_type: number
      length: 2

  - 18:  # op_preference3
      option_type: number
      length: 2

  - 19:  # literal_position
      option_type: number
      length: 2

  - 20:  # array_declaration1
      option_type: number
      length: 2

  - 21:  # array_declaration2
      option_type: number
      length: 2

  - 22:  # continue_jump1
      option_type: number
      length: 3

  - 23:  # continue_jump2
      option_type: number
      length: 3

  - 24:  # redundant_code1
      option_type: number
      length: 2

  - 25:  # redundant_code2
      option_type: number
      length: 2

- IfElseBodyOrderStyler:
  - short_body_comes_first:  # control `shortBodyComesFirst`
      option_type: bool

- NamingStyler:
  - case_format:  # control `caseFormat`
      option_type: enum
      options:
        - UPPER_UNDERSCORE
        - LOWER_UNDERSCORE
        - UPPER_CAMEL
        - LOWER_CAMEL

  - brief:  # control `maxLength`
      option_type: bool
